# Generated by Django 5.2.6 on 2025-09-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_escrow', 'In Escrow'), ('complete', 'Complete'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
