# Generated by Django 5.2.6 on 2025-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_new_password_alter_transaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_upi_id',
            field=models.CharField(blank=True, help_text="Seller's UPI ID for payouts", max_length=100, null=True),
        ),
    ]
